"""
Brain package initialization for Synapse.
"""

from .schema import (
    ActionType,
    Task,
    TaskStatus,
    PlanStatus,
    ExecutionPlan,
    ExecutionResult,
    RiskLevel,
    ErrorCode,
    InputSource,
    CoordinateSpace,
    MouseButton,
    StandardLocation,
    Target,
    Condition,
    RetryPolicy,
    RollbackSpec,
    BaseActionParameters,
    SystemContext,
    WindowInfo,
    DisplayInfo,
    AudioDeviceInfo,
    NetworkInfo,
    ACTION_PARAM_REGISTRY,
)
from .orchestrator import Orchestrator

__all__ = [
    "ActionType",
    "Task",
    "TaskStatus",
    "PlanStatus",
    "ExecutionPlan",
    "ExecutionResult",
    "RiskLevel",
    "ErrorCode",
    "InputSource",
    "CoordinateSpace",
    "MouseButton",
    "StandardLocation",
    "Target",
    "Condition",
    "RetryPolicy",
    "RollbackSpec",
    "BaseActionParameters",
    "SystemContext",
    "WindowInfo",
    "DisplayInfo",
    "AudioDeviceInfo",
    "NetworkInfo",
    "ACTION_PARAM_REGISTRY",
    "Orchestrator",
]
