"""
Executor component of the Synapse pipeline.

Responsible for receiving an ExecutionPlan from the Brain (Orchestrator),
iterating through each Task, dispatching it to the appropriate sub-millisecond action handler,
and tracking the task execution status and results.
"""

import sys
from typing import Callable, Dict
from Brain.schema import ActionType, ExecutionPlan, Task, TaskStatus

# Ensure Windows terminal supports UTF-8, emojis, and Indic scripts
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from .actions import (
    launch_application,
    execute_shell_command,
    control_system_volume,
    control_system_brightness,
    open_browser_url,
    search_web_engine,
    scroll_page,
    press_key_or_shortcut,
    type_keyboard_text,
    click_on_screen,
    click_button_by_name,
    manage_active_window,
)


class Executor:
    """Executes tasks in an ExecutionPlan by routing to concrete action handlers with near-zero latency."""

    def __init__(self):
        # Register high-speed action dispatch table
        self._handlers: Dict[ActionType, Callable[..., str]] = {
            ActionType.OPEN_APP: self._handle_open_app,
            ActionType.OPEN_URL: self._handle_open_url,
            ActionType.SEARCH_WEB: self._handle_search_web,
            ActionType.RUN_COMMAND: self._handle_run_command,
            ActionType.WINDOW_CONTROL: self._handle_window_control,
            ActionType.MOUSE_SCROLL: self._handle_mouse_scroll,
            ActionType.KEY_PRESS: self._handle_key_press,
            ActionType.TYPE_TEXT: self._handle_type_text,
            ActionType.MOUSE_CLICK: self._handle_mouse_click,
            ActionType.CLICK_TEXT: self._handle_click_text,
            ActionType.SYSTEM_VOLUME: self._handle_system_volume,
            ActionType.SYSTEM_BRIGHTNESS: self._handle_system_brightness,
            ActionType.TTS_SPEAK: self._handle_tts_speak,
        }

    def execute_plan(self, plan: ExecutionPlan) -> ExecutionPlan:
        """
        Executes all tasks in the provided plan sequentially.
        
        Args:
            plan: The ExecutionPlan generated by the Brain.
        Returns:
            The mutated plan containing execution results and final statuses.
        """
        print(f"\n⚙️  [Executor] Starting execution for Plan ID: {plan.plan_id}")
        print(f"   Tasks to execute: {len(plan.tasks)}")

        for index, task in enumerate(plan.tasks, start=1):
            print(f"\n   ▶️ Task {index}/{len(plan.tasks)}: {task.description} ({task.action.value})")
            self.execute_task(task)

            if task.status == TaskStatus.SUCCESS:
                print(f"      ✅ Success: {task.result}")
            else:
                print(f"      ❌ Failed: {task.error}")

        print(f"\n🏁 [Executor] Plan execution finished.")
        return plan

    def execute_task(self, task: Task) -> Task:
        """Executes a single atomic Task."""
        handler = self._handlers.get(task.action)
        if not handler:
            task.status = TaskStatus.FAILED
            task.error = f"No handler registered for action type: {task.action}"
            return task

        task.status = TaskStatus.RUNNING
        try:
            result = handler(task.parameters)
            task.status = TaskStatus.SUCCESS
            task.result = result
        except Exception as e:
            task.status = TaskStatus.FAILED
            task.error = str(e)

        return task

    # ── Action Dispatch Wrappers ──

    def _handle_open_app(self, params: dict) -> str:
        app_name = params.get("app_name") or params.get("target")
        if not app_name:
            raise ValueError("Missing 'app_name' parameter in task.")
        return launch_application(app_name)

    def _handle_open_url(self, params: dict) -> str:
        url = params.get("url")
        if not url:
            raise ValueError("Missing 'url' parameter in task.")
        return open_browser_url(url)

    def _handle_search_web(self, params: dict) -> str:
        query = params.get("query")
        if not query:
            raise ValueError("Missing 'query' parameter in task.")
        engine = params.get("engine", "google")
        return search_web_engine(query, engine)

    def _handle_run_command(self, params: dict) -> str:
        command = params.get("command")
        if not command:
            raise ValueError("Missing 'command' parameter in task.")
        return execute_shell_command(command)

    def _handle_window_control(self, params: dict) -> str:
        action = params.get("action", "maximize")
        return manage_active_window(action)

    def _handle_mouse_scroll(self, params: dict) -> str:
        direction = params.get("direction", "down")
        intensity = params.get("intensity", 5)
        return scroll_page(direction=direction, intensity=intensity)

    def _handle_key_press(self, params: dict) -> str:
        key = params.get("key") or params.get("shortcut")
        if not key:
            raise ValueError("Missing 'key' parameter in task.")
        return press_key_or_shortcut(key)

    def _handle_type_text(self, params: dict) -> str:
        text = params.get("text", "")
        return type_keyboard_text(text)

    def _handle_mouse_click(self, params: dict) -> str:
        x = params.get("x")
        y = params.get("y")
        clicks = params.get("clicks", 1)
        button = params.get("button", "left")
        return click_on_screen(x=x, y=y, clicks=clicks, button=button)

    def _handle_click_text(self, params: dict) -> str:
        button_name = params.get("button_name", "Continue")
        return click_button_by_name(button_name)

    def _handle_system_volume(self, params: dict) -> str:
        action = params.get("action", "up")
        steps = params.get("steps", 3)
        return control_system_volume(action=action, steps=steps)

    def _handle_system_brightness(self, params: dict) -> str:
        action = params.get("action", "up")
        step = params.get("step", 10)
        return control_system_brightness(action=action, step=step)

    def _handle_tts_speak(self, params: dict) -> str:
        text = params.get("text", "")
        print(f"      🗣️  [TTS Speech]: \"{text}\"")
        return f"Spoke: '{text}'"
